import { Navbar } from "@/components/Nav";
import "./globals.css";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import getCurrentUser from "@/utils/actions";
import { SafeUser } from "@/types";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={nunito.className}>
        <div className="w-full pb-4 px-4 md:px-8 xl:px-16 max-w-[2500px]">
          <Navbar currentUser={currentUser} />
          {children}
        </div>
      </body>
    </html>
  );
}
